---
SAGEMAKER_SHARED_S3_PREFIX: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/sagemaker-robomaker-artifacts"
CAR_NAME: "Sagar_Model"
KINESIS_VIDEO_STREAM_NAME: "dr-kvs-372026249783-20210720173320-5e2064d2-6448-42cc-89ee-ef93f2b4309c"
TRAINING_JOB_ARN: "arn:aws:deepracer:us-east-1:932412654770:training_job/_epgfBHcT_qh2WYCncK9hg"
REWARD_FILE_S3_KEY: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/reward_function.py"
MP4_S3_OBJECT_PREFIX: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/videos/training/training-20210720173320-_epgfBHcT_qh2WYCncK9hg"
WORLD_NAME: "thunder_hill_pro"
SAGEMAKER_SHARED_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
RACE_TYPE: "TIME_TRIAL"
MODEL_METADATA_FILE_S3_KEY: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/model_metadata.json"
BODY_SHELL_TYPE: "deepracer"
TARGET_REWARD_SCORE: "None"
CHANGE_START_POSITION: "true"
METRICS_S3_OBJECT_KEY: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/metrics/training/training-20210720173320-_epgfBHcT_qh2WYCncK9hg.json"
AWS_REGION: "us-east-1"
NUMBER_OF_EPISODES: "0"
S3_KMS_CMK_ARN: "arn:aws:kms:us-east-1:372026249783:key/55056074-cb58-42d8-8f6e-ad357cf4b47e"
METRIC_NAMESPACE: "AWSDeepRacer"
ALTERNATE_DRIVING_DIRECTION: "false"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID: "372026249783"
SIMTRACE_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
METRICS_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
MP4_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SIMTRACE_S3_PREFIX: "data-ca0ed465-a8d5-477b-a543-844b573c0ee6/models/sagarmodel/sim-trace/training"
JOB_TYPE: "TRAINING"
METRIC_NAME: "TrainingRewardScore"
CAR_COLOR: "Black"
